### ISSUE TITLE
New users registered through socialite cannot order

### ISSUE THREAD

**Issue by ealvarezdetoledo** [tastyigniter/ti-ext-socialite#1]
**Expected behavior:**
(Describe expected behavior here)

New User is registered through socialite, and is able to order straight away.

**Actual behavior:**
(Describe actual behavior here)

New user is registered through socialite, it is not placed in any customer group, it's account is not automatically activated, and it cannot order. 

**Reproduce steps:**
(Describe the steps to reproduce the problem here)
https://fasty.me/laravel/
Register with any social acct
Try to order

**Version:**
(TastyIgniter version number) Last available version

**Additional Information:**
(Additional information, if any)

**Comment by babelattke** [comment]
I just added the PR for that change, it will assign the user to the default group and enabled by default.

_/models/Provider.php_

**Comment by sampoyigi** [comment]
Fixed: #1
