### ISSUE TITLE
Does not differentiate between first and lastname

### ISSUE THREAD

**Issue by ealvarezdetoledo** [tastyigniter/ti-ext-socialite#4]
**Expected behavior:**
When new user is registered, its First and Last name are properly written in the TI database.

**Actual behavior:**
Full name is stored as First  name

**Reproduce steps:**

**Version:**
Latest (~3.0)

**Additional Information:**
(Additional information, if any)

**Comment by ealvarezdetoledo** [comment]
Issue seems to be in line 89 of /models/Provider.php 

Should be adjusted by:

   case 'facebook':
      $first_name = $providerUser->offsetGet('first_name');
      $last_name = $providerUser->offsetGet('last_name');
      break;

   case 'google':
      $first_name = $providerUser->offsetGet('given_name');
      $last_name = $providerUser->offsetGet('family_name');
      break;

**Comment by ealvarezdetoledo** [comment]
So apparently the problem is that, as coded, the driver will no return these fields, thus you need to specify which fields you want FB to resturn: 

//get the driver and set desired fields
$driver = Socialite::driver('facebook')
                ->fields([
                    'name', 
                    'first_name', 
                    'last_name', 
                    'email', 
                    'gender', 
                    'verified'
                ]);
// retrieve the user
$user = $driver->user();

**Comment by BreakSecurity** [comment]
@ealvarezdetoledo Can you make a PR? Whit the fixes

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.

**Comment by antoniozh** [comment]
It seems to me that the case is not fixed yet, since only the name field is filled for user. #8 fixes last name issue for me.
